@startuml

actor User

participant ":UniTasker" as UniTasker
box "command"
participant ":CommandParser" as CommandParser
participant ":ReorderCommand" as ReorderCommand
end box
participant ":UI" as UI
participant ":Storage" as Storage
participant ":AppContainer" as AppContainer

User -> UniTasker : "reorder todo 1 1 2"
activate UniTasker

UniTasker -> CommandParser : parse(line)
activate CommandParser

CommandParser -> ReorderCommand : create
activate ReorderCommand
ReorderCommand --> CommandParser
deactivate ReorderCommand

CommandParser --> UniTasker :
deactivate CommandParser

UniTasker -> ReorderCommand : execute(container)
activate ReorderCommand



ReorderCommand -> AppContainer : reorderTodo(...)
activate AppContainer
AppContainer --> ReorderCommand :
deactivate AppContainer

ReorderCommand -> ReorderCommand : saveData()
activate ReorderCommand
ReorderCommand -> Storage : save(categories)
activate Storage
Storage --> ReorderCommand :
deactivate Storage
deactivate ReorderCommand

ReorderCommand -> UI : printReordered(...)
activate UI
UI --> ReorderCommand
deactivate UI

ReorderCommand --> UniTasker :
deactivate ReorderCommand

UniTasker --> User :
deactivate UniTasker

@enduml